export const ACTIONS = {
  COMPLETE_ONBOARDING: "COMPLETE_ONBOARDING",
  ADD_CRAVING_LOG: "ADD_CRAVING_LOG",
  ADD_RELAPSE_LOG: "ADD_RELAPSE_LOG",
  ADD_JOURNAL_ENTRY: "ADD_JOURNAL_ENTRY",
  UPDATE_REASONS: "UPDATE_REASONS",
  TOGGLE_PREMIUM: "TOGGLE_PREMIUM",
  ACTIVATE_RECOVERY: "ACTIVATE_RECOVERY",
  DEACTIVATE_RECOVERY: "DEACTIVATE_RECOVERY",
  UPDATE_NOTIFICATION_SETTINGS: "UPDATE_NOTIFICATION_SETTINGS",
  RESET_APP: "RESET_APP",
} as const;
